[package]
name = "ic-registry-common-proto"
version = "0.8.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
prost = "0.9.0"
prost-types = "0.9.0"

[build-dependencies]
prost-build = "0.9.0"
