[package]
name = "ic-test-utilities"
version = "0.8.0"
edition = "2018"

[dependencies]
async-trait = "0.1.36"
bincode = "1.2.1"
ed25519-dalek = "1.0.1"
hex-literal = "0.2.1"
ic-base-types = { path = "../types/base_types" }
ic-btc-types-internal = { path = "../bitcoin/types/internal" }
ic-canister-client = { path = "../canister_client" }
ic-config = { path = "../config" }
ic-consensus = { path = "../consensus" }
ic-consensus-message = { path = "../consensus/message" }
ic-crypto = { path = "../crypto" }
ic-crypto-internal-types = { path = "../crypto/internal/crypto_lib/types" }
ic-crypto-sha = { path = "../crypto/sha" }
ic-crypto-test-utils = { path = "../crypto/test_utils" }
ic-crypto-tls-interfaces = { path = "../crypto/tls_interfaces" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-embedders = { path = "../embedders" }
ic-execution-environment = { path = "../execution_environment" }
ic-interfaces = { path = "../interfaces" }
ic-interfaces-bitcoin-adapter-client = { path = "../interfaces/bitcoin_adapter_client" }
ic-interfaces-p2p = { path = "../interfaces/p2p" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-client-fake = { path = "../registry/fake" }
ic-registry-client-helpers = { path = "../registry/helpers" }
ic-registry-common = { path = "../registry/common" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-proto-data-provider = { path = "../registry/proto_data_provider" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-system-api = { path = "../system_api" }
ic-types = { path = "../types/types" }
ic-types-test-utils = { path = "../types/types_test_utils" }
ic-universal-canister = { path = "../universal_canister/lib" }
ic-wasm-types = { path = "../types/wasm_types" }
lazy_static = "1.4.0"
maplit = "1.0.2"
mockall = "0.7.2"
nix = "0.23.0"
phantom_newtype = { path = "../phantom_newtype" }
prometheus = { version = "0.12.0", features = [ "process" ] }
proptest = "0.9.4"
rand = "0.7.3"
rand_chacha = "0.2.2"
rand_core = "0.5.1"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_cbor = "0.11.1"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
slog-scope = "4.1.2"
slog-term = "2.6.0"
socket2 = { version = "0.3.19", features = ["reuseport"] }
strum = "0.23.0"
tempfile = "3.1.0"
tokio = { version = "1.15.0" }
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }

[dev-dependencies]
assert_matches = "1.3.0"
ic-artifact-pool = { path = "../artifact_pool" }
rusty-fork = "0.3.0"
