[guest-os-diskimg]
input = [
    "../../artifacts/release/replica.gz",
    "../../artifacts/release/orchestrator.gz",
    "../../artifacts/release/canister_sandbox.gz",
    "../../artifacts/release/sandbox_launcher.gz",
    "../../artifacts/release/vsock_agent.gz",
    "../../artifacts/release/state-tool.gz",
    "../../artifacts/release/ic-consensus-pool-util.gz",
    "../../artifacts/release/ic-crypto-csp.gz",
    "../../artifacts/release/ic-regedit.gz",
    "scripts/*",
    "../../gitlab-ci/src/job_scripts/*",
    "bootloader/*",
    "rootfs/**/*",
    ]

# This is repeated verbatim. Maybe we need to use YAML instead of TOML to avoid this.
[guest-os-diskimg-dev]
input = [
    "../../artifacts/release/replica.gz",
    "../../artifacts/release/orchestrator.gz",
    "../../artifacts/release/canister_sandbox.gz",
    "../../artifacts/release/sandbox_launcher.gz",
    "../../artifacts/release/vsock_agent.gz",
    "../../artifacts/release/state-tool.gz",
    "../../artifacts/release/ic-consensus-pool-util.gz",
    "../../artifacts/release/ic-crypto-csp.gz",
    "../../artifacts/release/ic-regedit.gz",
    "scripts/*",
    "../../gitlab-ci/src/job_scripts/*",
    "bootloader/*",
    "rootfs/**/*",
]

# This is repeated verbatim again.
[guest-os-diskimg-dev-malicious]
input = [
    "../../artifacts/release/replica.gz",
    "../../artifacts/release/orchestrator.gz",
    "../../artifacts/release/canister_sandbox.gz",
    "../../artifacts/release/sandbox_launcher.gz",
    "../../artifacts/release/vsock_agent.gz",
    "../../artifacts/release/state-tool.gz",
    "../../artifacts/release/ic-consensus-pool-util.gz",
    "../../artifacts/release/ic-crypto-csp.gz",
    "../../artifacts/release/ic-regedit.gz",
    "scripts/*",
    "../../gitlab-ci/src/job_scripts/*",
    "bootloader/*",
    "rootfs/**/*",
]

[guest-os-updateimg-build]
input = [
    "../../artifacts/release/replica.gz",
    "../../artifacts/release/orchestrator.gz",
    "../../artifacts/release/canister_sandbox.gz",
    "../../artifacts/release/sandbox_launcher.gz",
    "../../artifacts/release/vsock_agent.gz",
    "../../artifacts/release/state-tool.gz",
    "../../artifacts/release/ic-consensus-pool-util.gz",
    "../../artifacts/release/ic-crypto-csp.gz",
    "../../artifacts/release/ic-regedit.gz",
    "scripts/*",
    "../../gitlab-ci/src/job_scripts/*",
    "bootloader/*",
    "rootfs/**/*",
    ]


[guest-os-updateimg-build-dev]
input = [
    "../../artifacts/release/replica.gz",
    "../../artifacts/release/orchestrator.gz",
    "../../artifacts/release/canister_sandbox.gz",
    "../../artifacts/release/sandbox_launcher.gz",
    "../../artifacts/release/vsock_agent.gz",
    "../../artifacts/release/state-tool.gz",
    "../../artifacts/release/ic-consensus-pool-util.gz",
    "../../artifacts/release/ic-crypto-csp.gz",
    "../../artifacts/release/ic-regedit.gz",
    "scripts/*",
    "../../gitlab-ci/src/job_scripts/*",
    "bootloader/*",
    "rootfs/**/*",
    ]
