[package]
name = "ic-registry-client"
version = "0.8.0"
edition = "2018"

[dependencies]
anyhow = "1.0.31"
ic-config = { path = "../../config" }
ic-interfaces = { path = "../../interfaces" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-common-proto = { path = "../proto" }
ic-registry-client-helpers = { path = "../helpers" }
ic-registry-provisional-whitelist = { path = "../provisional_whitelist" }
ic-registry-routing-table = { path = "../routing_table" }
ic-registry-subnet-features = { path = "../subnet_features" }
ic-registry-transport = { path = "../transport" }
ic-registry-keys = { path = "../keys" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
prost = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
slog = { version = "2.5.2", features = [
    "nested-values",
    "max_level_trace",
    "release_max_level_debug",
] }
thiserror = "1.0"
url = { version = "2.1.1", features = ["serde"] }

[dev-dependencies]
assert_matches = "1.3.0"
ic-registry-proto-data-provider = { path = "../proto_data_provider" }
ic-test-utilities = { path = "../../test_utilities" }
tempfile = "3.0"
