# The lifeline is a motoko canister.
#
# This Cargo file exists so that we can invoke `moc`, the motoko compiler, at rust compile time.
# src/lib.rs is a rust wrapper library that exposes the lifetime.wasm as a constant, for testing.

[package]
name = "lifeline"
version = "0.8.0"
edition = "2018"

[build-dependencies]
ic-nns-constants = { path = "../../constants" }
ic-base-types = { path = "../../../types/base_types" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
wabt = "0.10.0"
candid = "0.7.4"
dfn_candid = {path="../../../rust_canisters/dfn_candid"}
ic-ic00-types = {path="../../../types/ic00_types"}
ic-nns-common ={path="../../common"}
ic-nns-handler-root={path="../root"}
