# The lifeline is a motoko canister.
#
# This Cargo file exists so that we can invoke `moc`, the motoko compiler, at rust compile time.
# src/lib.rs is a rust wrapper library that exposes the lifetime.wasm as a constant, for testing.

[package]
name = "lifeline"
version = "0.8.0"
edition = "2018"

[build-dependencies]
ic-nns-constants = { path = "../../constants" }
ic-base-types = { path = "../../../types/base_types" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
# TODO(EXC-220)
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", rev = "b4d778802976f10494411388e48a784d4d015bbb" }
candid = "0.6.15"
dfn_candid = {path="../../../rust_canisters/dfn_candid"}
ic-ic00-types = {path="../../../types/ic00_types"}
ic-nns-common ={path="../../common"}
ic-nns-handler-root={path="../root"}
