[package]
name = "process_manager"
version = "0.8.0"
edition = "2018"

[dependencies]
futures = "0.3.6"
nix = "0.23.0"
tokio = { version = "1.15.0", features = ["full"] }
tokio-stream = { version = "0.1.3", features = ["io-util"] }

[dev-dependencies]
assert_matches = "1.3.0"

[lib]
name = "process_manager"
path = "src/lib.rs"
