[package]
name = "ic-p8s-service-discovery"
version = "0.8.0"
edition = "2018"

[dependencies]
anyhow = "1.0.31"
elastic_common_schema = { path = "../elastic_common_schema" }
erased-serde = "0.3.11"
futures-util = "0.3.5"
gflags = "0.3.7"
gflags-derive = "0.1"
humantime = "2.0"
humantime-serde = "1.0"
hyper = { version ="0.14.5", features = ["full"] }
ic-base-server = { path = "../base/server" }
ic-p8s-service-discovery-log = { path = "./log" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-types = { path = "../types/types" }
lazy_static = "1.4.0"
parse_int = "0.4.0"
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
tempfile = "3.1.0"
slog = { version = "2.5.2", features = ["nested-values"] }
slog_derive = "0.2.0"
strum = { version = "0.19.5", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.9.0", features = ["full"] }
url = { version = "2.1.1", features = ["serde"] }
ic-crypto-utils-threshold-sig = { path = "../crypto/utils/threshold_sig" }

[dev-dependencies]
ic-test-utilities = { path = "../test_utilities" }
ic-registry-common = { path = "../registry/common" }
