[package]
name = "bazelifier"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.11.1", features = ["serde-json"] }
toml = "0.5.9"
pathdiff = "0.2.1"
serde = { version = "1.0.137", features = ["derive"] }
eyre = "0.6.8"
clap = { version = "3.1.18", features = ["derive"] }
