[package]
name = "bigger-project"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
edition = "2018"

[dependencies]
reqwest = "0.11"
tokio = { version = "1.2.0", features = ["macros"] }
