[package]
name = "ic-canister-http-adapter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-stream = "0.3.2"
clap = { version = "3.1.6", features = ["derive"] }
futures = "0.3.17"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5.0"
ic-async-utils = { path = "../../async_utils" }
ic-canister-http-adapter-service = { path = "../adapter_service"}
ic-config = { path = "../../config" }
ic-logger = { path = "../../monitoring/logger" }
ic-protobuf = { path = "../../protobuf" }
prost = "0.9"
rand = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.7.0"
slog-async = "2.7.0"
tempfile = "3.3.0"
thiserror = "1.0.26"
tokio = { version = "1.15.0", features = ["full"] }
tonic = "0.6.2"
tower =  { version = "0.4.8", features = ["load-shed", "limit", "steer"] }

[dev-dependencies]
uuid = { version = "0.8.2", features = ["v4"] }