[package]
name = "ic-btc-adapter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "0.27.0", features = ["default", "use-serde", "rand"] }
clap = "=3.0.0-beta.2"
futures = "0.3.17"
hex = "0.4.2"
ic-async-utils = { path = "../../async_utils" }
ic-protobuf = { path = "../../protobuf" }
prost = "0.9"
rand = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.7.0"
slog-term = "2.8.0"
thiserror = "1.0.26"
tokio = { version = "1.15.0", features = ["full"] }
tokio-socks = "0.5.1"
tonic = "0.6.2"

[build-dependencies]
prost-build = "0.9.0"
tonic-build = "0.6.2"
