[package]
name = "ic-btc-adapter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = { version = "0.28.1", features = ["default", "use-serde", "rand"] }
clap = { version = "3.1.6", features = ["derive"] }
futures = "0.3.17"
hashlink = "0.8.0"
hex = "0.4.2"
http = "0.2"
ic-async-utils = { path = "../../async_utils" }
ic-btc-service = { path = "../service" }
ic-btc-validation = { path = "../validation" }
ic-config = { path = "../../config" }
ic-logger = { path = "../../monitoring/logger" }
parking_lot = "0.11.1"
prost = "0.10.4"
rand = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = "2.7.0"
slog-async = "2.7.0"
thiserror = "1.0.26"
tokio = { version = "1.15.0", features = ["full", "macros"] }
tokio-socks = "0.5.1"
tonic = "0.7.2"
tower = { version = "0.4.11", features = ["util"], optional = true }

[dev-dependencies]
tempfile = "3.3.0"

[[bin]]
name = "adapter-stress-test"
path = "src/stress_test.rs"
required-features = ["tower"]
