# This file will be dynamically included into the child pipeline if necessary.
# For instance, if there are changes in the "prod" directory.
# The following parts of the job may be overridden in gen_gitlab_cargo_pipeline.py:
# - stage
# - needs
# - GIT_REVISION and possibly some other variables

prod-generic-test:
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline
  # we modify stage in gen_gitlab_cargo_pipeline.py
  stage: prod-tests
  tags:
    - ic-prod-tests
    - docker
    - ubuntu
  needs:
    - guest-os-diskimg-dev
    - generic-guest-os-diskimg
    - cargo-build-canisters
    - cargo-build-release-linux-native
    - artifacts-upload-to-s3
  resource_group: $CDPRNET
  artifacts:
    paths:
    - artifacts/results
  timeout: 30m
  retry:
    max: 1
    when:
      - always
  variables:
    GIT_REVISION: $CI_COMMIT_SHA
  script:
    - |
      set -xeuo pipefail
      # Fake Git revision until we make testing scripts forget there is git.
      GIT_REVISION=$("$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/find-build-id.sh)
      export GIT_REVISION
      # Run generic test against $CDPRNET
      # * run it for 120 seconds
      # * require at least 100 RPS
      # * use requests of size 1KB
      capsule -i "gitlab-ci/**/*" -i "testnet/**/*" -t "${GIT_REVISION}" -- \
      testnet/tests/scripts/generic.sh "$CDPRNET" 120 100 1k artifacts/results
