include:
- local: /gitlab-ci/config/00--child-pipeline-root.yml

.ubuntu-nix-docker-protected:
  image:
    # Use the docker image without nix-shell
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:8daefe7e42c6a773d667655c39bc01e7a58361d9960e15ac54eb7900c59eb7ac"
  extends:
    - .ubuntu-nix-docker
  tags:
    - dfinity-launch
