bazel-test-all:
  extends:
    - .bazel-rules-pipeline
    - .ubuntu-nix-docker
  tags:
    - dfinity
    - docker
    - ubuntu
    # Run in ZH since BuildFarm is in ZH
    - zh
  image:
    # use the docker image without nix-shell as docker-run uses it too.
    name: "registry.gitlab.com/dfinity-lab/core/docker/ic-build:2022-05-24-c53836a52-be8ff12c4b27144189484417a003ae802bfcab93"
  stage: test
  needs: []
  artifacts:
    paths:
      - bazel-build-log*.json
  script:
    - set -euo pipefail
    - bazel version
    - bazel test --config ci ... 2>&1 | sed 's/\(.*Streaming build results to:.*\)/\o33[92m\1\o33[0m/'
