docker-build-ic-bin:
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline
  needs: []
  stage: cargo-build
  artifacts:
    paths:
      - artifacts
  script:
    - |
      set -euo pipefail
      gitlab-ci/tools/docker-build-ic -a=b,c

docker-build-ic-img:
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline
  needs:
    - artifacts-upload-to-s3
  stage: guest-os-build
  script:
    - |
      set -euo pipefail
      echo "Pipeline source: ${CI_PIPELINE_SOURCE}"
      VERSION=$(cat VERSION)
      export VERSION

      # release
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="${VERSION}" --remote-path="release" \
          --out="artifacts/release"
      # canisters
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="${VERSION}" --remote-path="canisters" \
          --out="artifacts/canisters"

      capsule -v -t "${VERSION}" -- \
      gitlab-ci/tools/docker-build-ic -a=i
      # we only collect artifacts/docker-build-ic/icos
      rm -rf artifacts/docker-build-ic/{canisters,release}
      rm -rf artifacts/{canisters,release}
