.cargo-clippy-fast-path:
  extends:
    - .rules-merge-branch-only
  needs: []  # don't wait on other jobs
  stage: test
  variables:
    BUILD_COMMAND: "$CI_PROJECT_DIR/gitlab-ci/src/rust_lint/lint.sh"

cargo-clippy-fast-path-linux:
  extends:
    - .ubuntu-nix-docker
    - .cargo-clippy-fast-path

cargo-clippy-fast-path-darwin:
  extends:
    - .macos-nix-native
    - .cargo-clippy-fast-path

