docker-build-ic:
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline
  needs: []
  stage: test
  artifacts:
    paths:
      - artifacts
  script:
    - |
      set -euo pipefail
      gitlab-ci/tools/docker-build-ic
