docker-build-ic:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  needs: []
  stage: test
  artifacts:
    paths:
      - artifacts
  script:
    - |
      set -euo pipefail

      # this builds all the artifacts (binaries, canisters & icos)
      # docker build image is also build (not using docker build cache)
      gitlab-ci/tools/docker-build-ic

      # print sha256sum
      cd artifacts/docker-build-ic
      echo "! SHA256 of binaries !"
      find ./release -type f -exec sha256sum {} \;
      echo "! SHA256 of canisters !"
      find ./canisters -type f -exec sha256sum {} \;
      echo "!!! SHA256 of ICOS !!!"
      find ./icos -type f -exec sha256sum {} \;

      # avoid exceeding gitlab's artifacts size limit
      rm -rf icos

      # artifacts (canisters & binaries) are used for build determinism tests
