bazel-test-all:
  extends:
    - .bazel-rules-pipeline
    - .ubuntu-nix-docker
  tags:
    - dfinity
    - docker
    - ubuntu
    # Run in ZH since BuildFarm is in ZH
    - zh
  stage: test
  needs: []
  artifacts:
    paths:
      - bazel-build-log*.json
  script:
    - set -euo pipefail
    - bazel version
    - bazel test --config ci ...
