legacy-system-tests:
  extends: .cargo-build-docker
  # System tests are very flaky due to replica non-determinism.
  retry: 2
  stage: cargo-test
  needs:
    - cargo-build-canisters
    - cargo-build-release-linux-native
    - cargo-build-release-linux-native-nd
    - cargo-build-release-linux-native-malicious
  artifacts:
    paths:
      - replica-logs/
      - junit_data/
      - coredumps/
      - runtime-stats.json
    when: always
    expire_in: 1 week
    reports:
      junit: test_report.xml
  variables:
      BLOCKING: "blocking"
      TEST_RUNNER_ARGS: "--experimental --jobs 6 --timeout 720s --ready-timeout 90s --runtime-stats ${CI_PROJECT_DIR}/runtime-stats.json --tee-replica-logs-base-dir ${CI_PROJECT_DIR}/replica-logs --skip staging -v"
      RUST_BACKTRACE: 1
  script:
    - |
      # Capsule for system tests is configured in Capsule.toml
      capsule -v -- "${CI_PROJECT_DIR}/gitlab-ci/src/job_scripts/system-tests.sh"

ic-ref-test:
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline
  stage: cargo-test
  retry: 2
  needs:
    - cargo-build-release-linux-native
    - cargo-build-release-linux-native-nd
  artifacts:
    when: always
    paths:
      - rs/report.html
      - rs/replica.stdout
      - rs/replica.stderr
    reports:
      junit: rs/ic-ref-test.xml
  variables:
      BLOCKING: "non-blocking"
      TEST_RUNNER_ARGS: "--skip staging_"
      USE_APP_SUBNET: "false"
      ALLOW_FAILURE: "true"
  parallel:
    matrix:
      - IC_REF_VERSION: "0_16"
      - IC_REF_VERSION: "0_17"
      - IC_REF_VERSION: "0_18"
  script:
    - |
      set -exuo pipefail

      # Fetch latest master build for upgrade tests.
      # Note that upgrade tests do *not* support malicious behavior as of now.
      mkdir ic-binary-base
      pushd ic-binary-base

      # Download the latest master artifacts before or including the branch's merge base.
      # Master is rebuilt every 2 hours, so in the worst case we may skip a few commits.
      # Most often this will be exactly the branch's merge base.
      "${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/rclone_download.py \
       --latest-to --merge-base=post-merge-tests-passed --remote-path=release --out=artifacts/release

      ls -lah
      cd artifacts/release
      BASE_BIN_DIR=$(pwd)
      ls -lah
      for f in replica orchestrator canister_sandbox; do
        gunzip "$f.gz"
        chmod +x "$f"
      done
      popd

      cd "${CI_PROJECT_DIR}/artifacts/release"

      ls -lah

      mkdir -p "${CI_PROJECT_DIR}/rs/local-bin"
      for f in replica orchestrator ic-test-bin canister_sandbox; do
        gunzip -k "$f.gz"
        chmod +x "$f"
        mv "$f" "${CI_PROJECT_DIR}/rs/local-bin/$f"
      done

      for f in replica orchestrator; do
        mv "${BASE_BIN_DIR}/$f" "${CI_PROJECT_DIR}/rs/local-bin/${f}_base"
      done

      cd "${CI_PROJECT_DIR}"

      ls -lah rs/local-bin


      export PATH="${CI_PROJECT_DIR}/rs/local-bin:$PATH"
      export LANG=C.UTF-8

      # IDX generally limits the nix-shell to only provide tool-chain dependencies. However, the ic-ref tests are
      # grandfathered into GitLab CI. Please speak with IDX team [#eng-idx] for guidance on how to plumb
      #  binary or code artifacts
      $SHELL_WRAPPER nix-shell -p "(import ./nix {}).ic-ref-$IC_REF_VERSION" --run ./tests/ic-ref-test/run

ic-ref-test-use-app-subnet:
  extends:
    - ic-ref-test
  variables:
    USE_APP_SUBNET: "true"
    ALLOW_FAILURE: "true"
  allow_failure: true
