# This file consolidates storage uploads for binaries and canisters.
# We need to defer it until the Build ID can be determined.
artifacts-upload-to-s3:
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  stage: guest-os-build
  needs:
    - cargo-build-canisters
    - cargo-build-release-linux-native
    - dfx-build-release-linux

    # these jobs only run on protected branches
    - job: cargo-build-release-darwin
      optional: true
    - job: dfx-build-release-darwin
      optional: true
  artifacts:
    paths:
    - VERSION
  script:
    - |
      set -exuo pipefail

      VERSION=$("${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/find-build-id.sh)
      echo "Build ID: ${VERSION}"
      echo "$VERSION" > VERSION

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "artifacts/release" release

      if [ -d artifacts/nix-release ]; then
        buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
          gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "artifacts/nix-release" nix-release/x86_64-darwin
      fi

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "artifacts/sdk-release" sdk-release

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "artifacts/canisters" canisters
