generic-guest-os-diskimg:
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  stage: guest-os-build
  needs:
    - artifacts-upload-to-s3
  script:
    - |
      set -xeuo pipefail

      VERSION=$(cat VERSION)
      export VERSION
      echo "Build ID: ${VERSION}"
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
          --git-rev="${VERSION}" --remote-path="release" \
          --out="artifacts/release"

      ls -lah /var/run/docker.sock; groups

      gunzip -c -d artifacts/release/boundary-node-control-plane.gz > artifacts/release/boundary-node-control-plane
      gunzip -c -d artifacts/release/boundary-node-prober.gz > artifacts/release/boundary-node-prober

      cd ic-os/generic-guestos

      mkdir -p build-out/disk-img/ build-tmp/
      buildevents cmd  "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" build-disk-img -- \
      capsule --passive -v -t "${VERSION}" -o build-tmp/disk.img -- \
      ./scripts/build-disk-image.sh -o build-tmp/disk.img -p root -v "${VERSION}" -x ../../artifacts/release/
      echo "${VERSION}" > build-tmp/version.txt
      ls -lah build-tmp

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" tar-build-out -- tar --sort=name --owner=root:0 --group=root:0 --mtime 0 --sparse -cvzf build-out/disk-img/disk-img.tar.gz -C build-tmp disk.img version.txt
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" tar-build-out -- tar --sort=name --owner=root:0 --group=root:0 --mtime 0 --sparse -cvf build-out/disk-img/disk-img.tar.zst --use-compress-program="zstd --threads=0 -10" -C build-tmp disk.img version.txt
      ls -lah build-out

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/openssl-sign.sh "build-out/disk-img"

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rsync-disk-img -- \
        "$CI_PROJECT_DIR"/gitlab-ci/tools/copy-disk "$CDPRNET" "generic"

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" build-out/disk-img/ generic-guest-os/disk-img

  artifacts:
    paths:
      - ic-os/generic-guestos/build-out/disk-img/*
    expire_in: 2 days
