guest-os-updateimg-build:
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  retry: 1
  stage: guest-os-build
  needs:
    - cargo-build-canisters   # For build-id
    - cargo-build-release-linux-native
  variables:
      BUILD_EXTRA_ARGS: ""
      BUILD_EXTRA_SUFFIX: ""
  script:
    - |
      set -xeuo pipefail

      BUILD_OUT="build-out/update-img${BUILD_EXTRA_SUFFIX}"
      UPLOAD_TARGET="guest-os/update-img${BUILD_EXTRA_SUFFIX}"
      VERSION=$("${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/find-build-id.sh)
      echo "Build ID: ${VERSION}"

      ls -lah /var/run/docker.sock; groups

      for f in replica orchestrator canister_sandbox vsock_agent state-tool ic-consensus-pool-util ic-crypto-csp ic-regedit ic-btc-adapter; do
        gunzip -c -d artifacts/release/$f.gz > artifacts/release/$f
      done

      cd ic-os/guestos
      mkdir -p "${BUILD_OUT}"

      # shellcheck disable=SC2086  # Expanding BUILD_EXTRA_ARGS into multiple parameters
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" build-disk-upgrade-img -- \
      capsule -v -t "$(openssl sha256 <<<${BUILD_EXTRA_ARGS}${BUILD_EXTRA_SUFFIX})" -t "${VERSION}" -o "${BUILD_OUT}/update-img.tar.gz" -- \
      ./scripts/build-update-image.sh -o "${BUILD_OUT}"/update-img.tar.gz -v "${VERSION}" -x ../../artifacts/release ${BUILD_EXTRA_ARGS}

      # Create a second upgrade image with different version number to ease testing with self upgrades
      # shellcheck disable=SC2086  # Expanding BUILD_EXTRA_ARGS into multiple parameters
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" build-disk-upgrade-img -- \
      capsule -v -t "$(openssl sha256 <<<${BUILD_EXTRA_ARGS}${BUILD_EXTRA_SUFFIX})" -t "${CI_JOB_IMAGE:-docker}" -t "${VERSION}" -o "${BUILD_OUT}/update-img-test.tar.gz" -- \
      ./scripts/build-update-image.sh -o "${BUILD_OUT}"/update-img-test.tar.gz -v "${VERSION}-test" -x ../../artifacts/release ${BUILD_EXTRA_ARGS}

      ls -lah "${BUILD_OUT}"

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/openssl-sign.sh "${BUILD_OUT}"

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" rclone -- \
        "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "${BUILD_OUT}" "${UPLOAD_TARGET}"

  artifacts:
    paths:
      - ic-os/guestos/build-out/update-img${BUILD_EXTRA_SUFFIX}/*
    expire_in: 2 days

# Build dev image. See diskimg for explanation.
guest-os-updateimg-build-dev:
  extends:
    - guest-os-updateimg-build
  variables:
      BUILD_EXTRA_ARGS: "-p root"
      BUILD_EXTRA_SUFFIX: "-dev"

# An exact dupe of the updateimg job for non-determinism testing.
guest-os-updateimg-build-determinism:
  extends:
    - guest-os-updateimg-build
  variables:
    BUILD_EXTRA_SUFFIX: "-determinism"
