rosetta-api-docker-image:
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-protected-branch-manual
  stage: guest-os-build
  needs:
    - cargo-build-release-linux-native
  script:
    - |
      set -exuo pipefail

      gunzip artifacts/release/ic-rosetta-api.gz
      chmod +x artifacts/release/ic-rosetta-api

      pushd "$(mktemp -d)"
      cp \
        "$CI_PROJECT_DIR"/artifacts/release/ic-rosetta-api \
        "$CI_PROJECT_DIR"/rs/rosetta-api/log_config.yml \
        .
      docker build \
        --build-arg RELEASE="$CI_COMMIT_SHA" \
        -f "$CI_PROJECT_DIR"/rs/rosetta-api/Dockerfile \
        -t dfinity/rosetta-api:"$CI_COMMIT_SHA" \
        .
      popd

      docker run --rm dfinity/rosetta-api:"$CI_COMMIT_SHA" --help

      ROSETTA_API_DATE=$(date +"%Y%m%d")
      ROSETTA_API_VERSION=$(grep -e '^version' "$CI_PROJECT_DIR"/rs/rosetta-api/Cargo.toml | sed -e 's|^version[ ]*=[ ]*"\([^"]*\)"|\1|g')

      docker tag dfinity/rosetta-api:"$CI_COMMIT_SHA" dfinity/rosetta-api:"$ROSETTA_API_DATE"
      docker tag dfinity/rosetta-api:"$CI_COMMIT_SHA" dfinity/rosetta-api:v"$ROSETTA_API_VERSION"
      docker tag dfinity/rosetta-api:"$CI_COMMIT_SHA" dfinity/rosetta-api:latest

      docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"

      docker push dfinity/rosetta-api:"$CI_COMMIT_SHA"
      docker push dfinity/rosetta-api:"$ROSETTA_API_DATE"
      docker push dfinity/rosetta-api:v"$ROSETTA_API_VERSION"
      docker push dfinity/rosetta-api:latest
