guest-os-updateimg-build:
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  retry: 1
  stage: guest-os-build
  needs:
    - artifacts-upload-to-s3
  variables:
      BUILD_EXTRA_ARGS: ""
      BUILD_EXTRA_SUFFIX: ""
  script:
    - |
      set -xeuo pipefail

      gitlab-ci/src/job_scripts/lib/guest-os-updateimg.sh

# Build dev image. See diskimg for explanation.
guest-os-updateimg-build-dev:
  extends:
    - guest-os-updateimg-build
  variables:
      BUILD_EXTRA_ARGS: "-t dev -p root"
      BUILD_EXTRA_SUFFIX: "-dev"

# An exact dupe of the updateimg job for non-determinism testing.
guest-os-updateimg-build-determinism:
  extends:
    - guest-os-updateimg-build
  variables:
    BUILD_EXTRA_SUFFIX: "-determinism"
