build-determinism-binaries:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: build-determinism-test
  allow_failure: true
  needs:
    - cargo-build-release-linux-native
    - docker-build-ic
  script:
    - |
      set -eux
      echo "cargo-build-release-linux-native:"
      cd artifacts/release
      # Build Determinism for GLOBIGNORE files will be handled by NNS and Testing & Verification team
      (
          sha256sum -- *.gz | tee SHAS
      )
      cd -
      echo "docker-build-ic:"
      cd artifacts/docker-build-ic/release
      (
          sha256sum -- *.gz | tee SHAS
      )
      cd -
      if [ "${CI_COMMIT_REF_PROTECTED:-}" != "true" ]; then
          set +x
          echo "Build determinism check compares two binaries built on a separate CI jobs:"
          echo " - cargo-build-release-linux-native"
          echo " - docker-build-ic"
          echo "Difference indicates that this MR introduced changes that break Build Determinism."
          echo -e "If this job fails, please identify the cause of breaking Build Determinism and fix it. \xF0\x9F\x99\x8F"
          set -x
      else
          echo "Difference indicates that Build Determinism is broken for binaries that differ!"
      fi
      diff -u artifacts/release/SHAS artifacts/docker-build-ic/release/SHAS


build-determinism-canisters:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: build-determinism-test
  allow_failure: true
  needs:
    - cargo-build-canisters
    - docker-build-ic
  script:
    - |
      set -eux
      echo "cargo-build-canisters:"
      cd artifacts/canisters
      # we ignore panics for now
      rm -f panics.wasm.gz sns-test-dapp-canister.wasm.gz
      sha256sum -- *.gz | tee SHAS
      cd -
      echo "docker-build-ic:"
      cd artifacts/docker-build-ic/canisters
      rm -f panics.wasm.gz sns-test-dapp-canister.wasm.gz
      sha256sum -- *.gz | tee SHAS
      cd -
      if [ "${CI_COMMIT_REF_PROTECTED:-}" != "true" ]; then
          set +x
          echo "Build determinism check compares two canister binaries built on a separate CI jobs:"
          echo " - cargo-build-canisters"
          echo " - docker-build-ic"
          echo "Difference indicates that this MR introduced changes that break Build Determinism."
          echo -e "If this job fails, please identify the cause of breaking Build Determinism and fix it. \xF0\x9F\x99\x8F"
          set -x
      else
          echo "Difference indicates that Build Determinism is broken for canister binaries that differ!"
      fi
      diff -u artifacts/canisters/SHAS artifacts/docker-build-ic/canisters/SHAS


build-determinism-update-img:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: build-determinism-test
  needs:
    - job: artifacts-upload-to-s3
    - job: guest-os-updateimg-build
      artifacts: false
    - job: guest-os-updateimg-build-determinism
      artifacts: false
  script:
    - |
      set -eux
      VERSION=$(cat VERSION)
      export VERSION

      for IMG in update-img update-img-determinism
      do
        # TODO: just fetch SHA file?
        "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py \
            --git-rev="${VERSION}" --remote-path="guest-os/${IMG}" --out="${IMG}"
        (cd "${IMG}"; sha256sum update-img.tar.gz | tee SHAS)
      done

      if [ "${CI_COMMIT_REF_PROTECTED:-}" != "true" ]; then
          set +x
          echo "Build determinism check compares two IC-OS guest update images built on a separate CI jobs:"
          echo " - guest-os-updateimg-build"
          echo " - docker-build-ic"
          echo "Difference indicates that this MR introduced changes that break Build Determinism for IC-OS guest image."
          echo -e "If this job fails, please identify the cause of breaking Build Determinism and fix it. \xF0\x9F\x99\x8F"
          set -x
      else
          echo "Difference indicates that Build Determinism is broken IC-OS guest image!"
      fi
      diff -u update-img/SHAS update-img-determinism/SHAS
