host-os-updateimg:
  needs:
    - artifacts-upload-to-s3
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  stage: host-os-build
  artifacts:
    paths:
      - ic-os/hostos/build-out/update-img${BUILD_EXTRA_SUFFIX}/*
    expire_in: 2 days
  variables:
      BUILD_EXTRA_ARGS: ""
      BUILD_EXTRA_SUFFIX: ""
      VERSION_SUFFIX: ""
  script:
    - |
      set -xeuo pipefail

      BUILD_OUT="build-out/update-img${BUILD_EXTRA_SUFFIX}"
      BUILD_TMP="build-tmp${BUILD_EXTRA_SUFFIX}"
      UPLOAD_TARGET="host-os/update-img${BUILD_EXTRA_SUFFIX}"
      VERSION=$(cat VERSION)${VERSION_SUFFIX}
      echo "Build ID: ${VERSION}"

      cd "${CI_PROJECT_DIR}"/ic-os/hostos
      # shellcheck disable=SC2086  # Expanding BUILD_EXTRA_ARGS into multiple parameters
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" build-host-update -- \
      capsule --passive -v -t "$(openssl sha256 <<<${BUILD_EXTRA_ARGS}${BUILD_EXTRA_SUFFIX})" -t "${VERSION}" -o "${BUILD_OUT}/**/*" -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/job_scripts/lib/host-os-updateimg.sh \
        "$BUILD_OUT" "$BUILD_TMP" "$UPLOAD_TARGET" "$VERSION"

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/openssl-sign.sh "$BUILD_OUT"

      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" rclone -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "$BUILD_OUT" "$UPLOAD_TARGET"

      # XXX FIXME: host-os build is not currently reproducible
      # extra placebo that logs as its inputs the outputs of the previous step
      # the intention is to cach non-determinism on host disk-img.tar.gz
      # placebo -v -c "${CI_JOB_NAME}--check" -i "disk-img.tar.gz" -- \
        # /bin/echo "Logged hashes of outputs to honeycomb via placebo."

host-os-updateimg-new:
  extends:
    - host-os-updateimg
  variables:
      BUILD_EXTRA_ARGS: ""
      BUILD_EXTRA_SUFFIX: ""
      VERSION_SUFFIX: "-new"
