host-os-diskimg:
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  stage: host-os-build
  needs: []
  artifacts:
    paths:
      - ic-os/hostos/build-out/disk-img${BUILD_EXTRA_SUFFIX}/*
    expire_in: 2 days
  variables:
      BUILD_EXTRA_ARGS: ""
      BUILD_EXTRA_SUFFIX: ""
  script:
    - |
      set -xeuo pipefail

      BUILD_OUT="build-out/disk-img${BUILD_EXTRA_SUFFIX}"
      BUILD_TMP="build-tmp${BUILD_EXTRA_SUFFIX}"
      UPLOAD_TARGET="host-os/disk-img${BUILD_EXTRA_SUFFIX}"
      VERSION=$(git rev-parse HEAD)
      export VERSION
      echo "Build ID: ${VERSION}"

      cd "${CI_PROJECT_DIR}"/ic-os/hostos
      # shellcheck disable=SC2086  # Expanding BUILD_EXTRA_ARGS into multiple parameters
      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" build-host-img -- \
      capsule --passive -v -t "$(openssl sha256 <<<${BUILD_EXTRA_ARGS}${BUILD_EXTRA_SUFFIX})" -t "${VERSION}" -o "${BUILD_OUT}/**/*" -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/job_scripts/lib/host-os-diskimg.sh \
        "$BUILD_OUT" "$BUILD_TMP" "$UPLOAD_TARGET" "$VERSION"

      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" rclone -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "$BUILD_OUT" "$UPLOAD_TARGET"
