host-os-iso:
  needs:
    - artifacts-upload-to-s3
    - guest-os-diskimg
    - host-os-diskimg
  dependencies:
    - artifacts-upload-to-s3
    - guest-os-diskimg
    - host-os-diskimg
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  stage: host-os-build
  allow_failure: true
  script:
    - |
      set -xeuo pipefail
      VERSION=$(cat VERSION)
      echo "Build ID: ${VERSION}"

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py --remote-path=guest-os --blessed-only --out=guestos --git-rev 0ef2aebde4ff735a1a93efa342dcf966b6df5061

      BUILD_OUT="ic-os/setupos/build-out"
      UPLOAD_TARGET="setup-os"

      ic-os/setupos/scripts/build-iso.sh \
        --guest-os=./guestos/disk-img/disk-img.tar.gz \
        --host-os=./ic-os/hostos/build-out/disk-img/host-disk-img.tar.gz \
        --output="$BUILD_OUT"

      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/openssl-sign.sh "$BUILD_OUT"

      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" rclone -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "$BUILD_OUT" "$UPLOAD_TARGET"
