build-determinism-binaries:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: build-determinism-test
  needs:
    - job: cargo-build-release-linux-native
      artifacts: false
    - job: docker-build-ic
      artifacts: false
    - job: artifacts-upload-to-s3
      artifacts: false
  variables:
    PATH0: "release"
    PATH1: "docker-build-ic/release"
  script:
    - |
      set -eExuo pipefail
      ./gitlab-ci/tools/build-diff.sh "$PATH0" "$PATH1"

build-determinism-canisters:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: build-determinism-test
  needs:
    - job: cargo-build-release-linux-native
      artifacts: false
    - job: docker-build-ic
      artifacts: false
    - job: artifacts-upload-to-s3
      artifacts: false
  variables:
    PATH0: "canisters"
    PATH1: "docker-build-ic/canisters"
  script:
    - |
      set -eExuo pipefail
      ./gitlab-ci/tools/build-diff.sh "$PATH0" "$PATH1"

build-determinism-guest-update-img:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: build-determinism-test
  needs:
    - job: guest-os-updateimg-build
      artifacts: false
    - job: docker-build-ic
      artifacts: false
  artifacts:
    paths:
      - artifacts
  variables:
    PATH0: "guest-os/update-img"
    PATH1: "docker-build-ic/guest-os/update-img"
  script:
    - |
      set -eExuo pipefail
      ./gitlab-ci/tools/build-diff.sh "$PATH0" "$PATH1"

build-determinism-host-update-img:
  extends:
    - .ubuntu-nix-docker-pinned-dc
    - .rules-parent-pipeline
  stage: build-determinism-test
  needs:
    - job: host-os-updateimg
      artifacts: false
    - job: host-os-updateimg-determinism
      artifacts: false
    - job: build-determinism-binaries
      artifacts: false
  artifacts:
    paths:
      - artifacts
  variables:
    PATH0: "host-os/update-img"
    PATH1: "host-os/update-img-determinism"
  script:
    - |
      set -eExuo pipefail
      ./gitlab-ci/tools/build-diff.sh "$PATH0" "$PATH1"
