prod-hourly-pipeline:
  extends: .rules-rollout-pipeline-auto
  needs: ["cargo-pipeline"]
  stage: prod-tests
  variables:
    CD_ENV: "HOURLY"
    TESTNET: "cdrc04"
    DISKIMG_BRANCH: "${CI_COMMIT_SHA}"
    PARENT_PIPELINE_ID: "${CI_PIPELINE_ID}"
  trigger:
    include:
      - local: gitlab-ci/config/00--prod-test-child-pipeline.yml
    strategy: depend

prod-nightly-pipeline:
  extends: .rules-rollout-pipeline-auto
  stage: prod-tests
  needs: ["cargo-pipeline"]
  variables:
    CD_ENV: "NIGHTLY"
    TESTNET1: "cdnightly"
    TESTNET2: "cdrc01"
    TESTNET3: "cdrc02"
    TESTNET4: "cdrc03"
    TESTNET5: "cdrc04"
    DISKIMG_BRANCH: "${CI_COMMIT_SHA}"
    PARENT_PIPELINE_ID: "${CI_PIPELINE_ID}"
  trigger:
    include:
      - local: gitlab-ci/config/00--prod-test-child-pipeline.yml
    strategy: depend

prod-hotfix-pipeline:
  extends: .rules-prod-hotfix-pipeline
  stage: prod-tests
  needs: ["cargo-pipeline"]
  variables:
    CD_ENV: "HOTFIX"
    TESTNET1: "cdhotfix01"
    TESTNET2: "cdhotfix02"
    TESTNET3: "cdhotfix03"
    DISKIMG_BRANCH: "${CI_COMMIT_SHA}"
    PARENT_PIPELINE_ID: "${CI_PIPELINE_ID}"
  trigger:
    include:
      - local: gitlab-ci/config/00--prod-test-child-pipeline.yml
    strategy: depend

prod-hourly-triggered:
  # Support running an hourly test in a "triggered" pipeline
  # https://docs.gitlab.com/ee/api/pipeline_triggers.html
  extends: .rules-rollout-pipeline-run-on-trigger
  needs: []
  stage: prod-tests
  variables:
    CD_ENV: "HOURLY"
    TESTNET: "cdrc03"
    DISKIMG_BRANCH: "${CI_COMMIT_SHA}"
    PARENT_PIPELINE_ID: "${CI_PIPELINE_ID}"
  trigger:
    include:
      - local: gitlab-ci/config/00--prod-test-child-pipeline.yml
    strategy: depend

prod-nightly-triggered:
  # Support running a nightly test in a "triggered" pipeline
  # https://docs.gitlab.com/ee/api/pipeline_triggers.html
  extends: .rules-rollout-pipeline-run-on-trigger
  needs: []
  stage: prod-tests
  variables:
    CD_ENV: "NIGHTLY"
    TESTNET1: "cdnightly"
    TESTNET2: "cdrc01"
    TESTNET3: "cdrc02"
    TESTNET4: "cdrc03"
    TESTNET5: "cdrc04"
    DISKIMG_BRANCH: "${CI_COMMIT_SHA}"
    PARENT_PIPELINE_ID: "${CI_PIPELINE_ID}"
  trigger:
    include:
      - local: gitlab-ci/config/00--prod-test-child-pipeline.yml
    strategy: depend

prod-hotfix-triggered:
  # Support running a nightly test in a "triggered" pipeline
  # https://docs.gitlab.com/ee/api/pipeline_triggers.html
  extends: .rules-rollout-pipeline-run-on-trigger
  needs: []
  stage: prod-tests
  variables:
    CD_ENV: "HOTFIX"
    TESTNET1: "cdhotfix01"
    TESTNET2: "cdhotfix02"
    TESTNET3: "cdhotfix03"
    DISKIMG_BRANCH: "${CI_COMMIT_SHA}"
    PARENT_PIPELINE_ID: "${CI_PIPELINE_ID}"
  trigger:
    include:
      - local: gitlab-ci/config/00--prod-test-child-pipeline.yml
    strategy: depend
