[package]
name = "ic-crypto-sha256"
version = "0.8.0"
edition = "2018"

[dependencies]
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
openssl = "0.10.29"
[target.'cfg(target_arch = "wasm32")'.dependencies]
sha2 = "0.9.1"

[dev-dependencies]
ic-crypto-internal-types = { path = "../internal/crypto_lib/types" }
