[package]
name = "ic-nns-integration-tests"
version = "0.8.0"
edition = "2018"

[[bin]]
name = "mem-utils-test-canister"
path = "test_canisters/mem_utils_test.rs"

[[bin]]
name = "governance-mem-test-canister"
path = "test_canisters/governance_mem_test_canister.rs"

# Dependencies required to compile the test canisters.
[dependencies]
async-trait = "0.1.42"
assert_matches = "1.4.0"
bytes = "1.0.1"
candid = "0.7.4"
cycles-minting-canister = {path = "../../nns/cmc"}
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_json = { path = "../../rust_canisters/dfn_json" }
futures = "0.3.8"
ic-base-types = { path = "../../types/base_types" }
ic-ledger-core = { path = "../../rosetta-api/ledger_core" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nns-common = { path = "../common" }
ic-nns-governance = { path = "../governance" }
ledger-canister = { path = "../../rosetta-api/ledger_canister" }
lifeline = { path = "../handlers/lifeline" }
prost = "0.10.4"
strum = "0.23.0"
lazy_static = "1.4.0"

# Dependencies required to compile the tests.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
canister-test = { path = "../../rust_canisters/canister_test" }
crossbeam = "0.8.0"
crossbeam-channel = "0.5.1"
ed25519-dalek = "1.0.1"
futures-util = "0.3.8"
hex = "0.4.2"
ic-canister-client = { path = "../../canister_client" }
ic-config = { path = "../../config" }
ic-crypto = { path = "../../crypto" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-error-types = {path="../../types/error_types"}
ic-ic00-types = {path="../../types/ic00_types"}
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nns-constants = { path = "../constants" }
ic-nns-handler-root = { path = "../handlers/root" }
ic-nns-gtc = { path = "../gtc" }
ic-nns-test-utils = { path = "../../nns/test_utils" }
ic-nns-test-utils-macros = { path = "../../nns/test_utils_macros" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-registry-transport = { path = "../../registry/transport" }
ic-test-utilities = { path = "../../test_utilities" }
ic-types = { path = "../../types/types" }
libsecp256k1 = "0.5.0"
maplit = "1.0.2"
on_wire = { path = "../../rust_canisters/on_wire" }
phantom_newtype = { path = "../../phantom_newtype" }
randomkit = "0.1.1"
rand = "0.7.3"
rand_core = "0.5.1"
registry-canister = { path = "../../registry/canister" }
rustc-hash = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
statrs = "0.15.0"
tokio = { version = "1.15.0", features = ["full"] }
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }
assert_matches = "1.3.0"
