[package]
name = "ic-canister-sandbox-backend-lib"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-base-types = { path = "../../types/base_types" }
ic-canister-sandbox-common  = { path = "../common" }
ic-cycles-account-manager = { path = "../../cycles_account_manager" }
ic-config = { path = "../../config" }
ic-embedders = { path = "../../embedders" }
ic-logger = { path = "../../monitoring/logger" }
ic-types = { path = "../../types/types" }
ic-replicated-state = { path = "../../replicated_state"}
ic-interfaces = { path = "../../interfaces" }
ic-wasm-types = { path = "../../types/wasm_types" }
ic-utils = { path = "../../utils"}
ic-sys = { path = "../../sys"}
ic-system-api = { path = "../../system_api" }
libc = "0.2.119"
libflate = "1.1.2"
memory_tracker = { path = "../../memory_tracker" }
nix = "0.23.0"
serde_json = "1.0.54"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
threadpool = "1.8.1"

[dev-dependencies]
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-test-utilities = { path = "../../test_utilities" }
mockall = "0.7.2"
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }

[features]
sigsegv_handler_checksum = [ "memory_tracker/sigsegv_handler_checksum" ]
