[package]
name = "ic-btc-canister"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27.1"
candid = "0.7.4"
byteorder = "1.4.3"
ic-protobuf = { path = "../../protobuf" }
ic-btc-types = { path = "../types/public" }
ic-replicated-state = { path = "../../replicated_state" }
lazy_static = "1.4.0"
prost = "0.9"
serde = "1.0.132"
stable-structures = { path = "../../stable-structures" }
ic-state-layout = { path = "../../state_layout" }

[build-dependencies]
prost-build = "0.9.0"

[[example]]
name = "build-utxo-set"
path = "src/examples/build_utxo_set.rs"

[dev-dependencies]
ic-btc-test-utils = { path = "../test-utils" }
bitcoin = {version = "0.27.1", features = ["rand"]} # needed for generating secp256k1 keys.
clap = {version = "3.1.9", features = ["derive"]}
maplit = "1.0.2"
tempfile = "3.2.0"
