[package]
name = "ic-btc-canister"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.27.1"
candid = "0.7.4"
byteorder = "1.4.3"
ic-protobuf = { path = "../../protobuf" }
ic-btc-types = { path = "../types/public" }
lazy_static = "1.4.0"
prost = "0.9"
serde = "1.0.132"
stable-structures = { path = "../../stable-structures" }

[build-dependencies]
prost-build = "0.9.0"

[[bin]]
name = "bitcoin-canister"
path = "src/main.rs"

[dev-dependencies]
bitcoin = {version = "0.27.1", features = ["rand"]} # needed for generating secp256k1 keys.
maplit = "1.0.2"
tempfile = "3.2.0"
