---
- name: install journalbeat repo
  apt:
    deb: "https://artifacts.elastic.co/downloads/beats/journalbeat/journalbeat-{{ journalbeat_version }}-amd64.deb"

- name: install journalbeat
  package:
    name: journalbeat
    state: present

- name: setup journalbeat config
  vars:
    testnet: "{{ inventory_file | dirname | basename }}"
  template:
    src: "journalbeat.yml"
    dest: "/etc/journalbeat/journalbeat.yml"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart journalbeat


- meta: flush_handlers

- name: ensure journalbeat started
  service:
    name: journalbeat
    state: started
    enabled: true
