include:
  - local: /gitlab-ci/config/00--child-pipeline-root-protected.yml

bar:
  extends: .cargo-crate-test

foo:
  extends: .cargo-crate-test
  variables:
    CARGO_TEST_FLAGS_EXTRA: "--release"

leaf1:
  extends: .cargo-crate-test

leaf2:
  extends: .cargo-crate-test

root:
  extends: .cargo-crate-test
