[package]
name = "ic-nns-test-utils"
version = "0.8.0"
edition = "2018"

[dependencies]
assert_matches = "1.3.0"
candid = "0.7.4"
canister-test = { path = "../../rust_canisters/canister_test" }
cycles-minting-canister = {path = "../../nns/cmc"}
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_json = { path = "../../rust_canisters/dfn_json" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
futures = "0.3.8"
ic-base-types={path="../../types/base_types"}
ic-canister-client = { path = "../../canister_client" }
ic-config = { path = "../../config" }
ic-crypto = {path = "../../crypto"}
ic-crypto-sha = {path = "../../crypto/sha"}
ic-nns-common = { path = "../common" }
ic-nns-constants = { path = "../constants" }
ic-nns-governance = { path = "../governance" }
ic-nns-gtc = { path = "../gtc" }
ic-nns-gtc-accounts = { path = "../gtc_accounts" }
ic-nns-test-keys = { path = "../test_keys" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nns-handler-root = { path = "../handlers/root" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-registry-transport = { path = "../../registry/transport" }
ic-test-utilities = { path = "../../test_utilities" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils" }
ledger-canister = {path = "../../rosetta-api/ledger_canister"}
lifeline = { path = "../handlers/lifeline" }
maplit = "1.0.2"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.9.0"
registry-canister = { path = "../../registry/canister"}
serde = { version = "1.0", features = ["derive"] }
