[package]
name = "ic-metrics-exporter"
version = "0.8.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14.18", features = ["full"] }
ic-config = { path = "../../config" }
ic-crypto-tls-interfaces = { path = "../../crypto/tls_interfaces" }
ic-interfaces = { path = "../../interfaces" }
ic-metrics = { path = "../metrics" }
ic-types = { path = "../../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
tokio = "1.15.0"
