[package]
name = "ic-embedders"
version = "0.8.0"
edition = "2018"

[dependencies]
anyhow = "1.0.31"
ic-config = { path = "../config" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-system-api = { path = "../system_api" }
ic-metrics = { path = "../monitoring/metrics" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-wasm-types = { path = "../types/wasm_types" }
libc = "0.2.91"
libflate = "1.1.2"
memory_tracker = { path = "../memory_tracker" }
nix = "0.23.0"
parity-wasm = { version = "0.42.2", features = [ "std", "multi_value", "bulk" ] }
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
wasmtime = { version = "0.37", default_features = false, features = ['cranelift', 'parallel-compilation', 'posix-signals-on-macos', 'wasm-backtrace'] }
wasmtime-environ = "0.37"
wasmtime-runtime = "0.37"


[dev-dependencies]
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-system-api = { path = "../system_api" }
ic-test-utilities = { path = "../test_utilities" }
lazy_static = "1.4.0"
maplit = "1.0.2"
proptest = "0.9.4"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
assert_matches = "1.3.0"
insta = "1.8.0"
pretty_assertions = "0.6.1"
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }


[[bin]]
name = "instrument-wasm"
path = "src/wasm_utils/instrument_wasm.rs"
