[package]
name = "phantom_newtype"
version = "0.8.0"
edition = "2018"

[dependencies]
candid = "0.7.4"
serde = "1.0.99"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }

[dev-dependencies]
serde_json = "1.0.40"
