[package]
name = "ic-interfaces-bitcoin-adapter-client"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-btc-types-internal = { path = "../../bitcoin/types/internal" }
strum = { version = "0.24", features = ["derive"] }
tonic = "0.6.2"
