[package]
name = "ic-sns-integration-tests"
version = "0.8.0"
edition = "2018"

# Dependencies required to compile the test canisters.
[dependencies]
candid = "0.7.4"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_json = { path = "../../rust_canisters/dfn_json" }
ledger-canister = { path = "../../rosetta-api/ledger_canister" }

# Dependencies required to compile the tests.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ic-canister-client = { path = "../../canister_client" }
ic-sns-governance = { path = "../governance" }
ic-crypto = { path = "../../crypto" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-sns-test-utils = { path = "../../sns/test_utils" }
ic-nns-constants = { path = "../../nns/constants" }
ic-types = { path = "../../types/types" }
ic-base-types={path="../../types/base_types"}
