[package]
name = "ic-sns-integration-tests"
version = "0.8.0"
edition = "2018"

[[bin]]
name = "sns-test-dapp-canister"
path = "test_canisters/test_dapp_canister.rs"

[[bin]]
name = "sns-governance-mem-test-canister"
path = "test_canisters/sns_governance_mem_test_canister.rs"

# Dependencies required to compile the test canisters.
[dependencies]
async-trait = "0.1.42"
byteorder = "1.4.3"
candid = "0.7.4"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_json = { path = "../../rust_canisters/dfn_json" }
hex = "0.4.3"
ic-base-types = { path = "../../types/base_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-nervous-system-common= {path = "../../nervous_system/common/"}
ic-sns-governance = { path = "../governance" }
ledger-canister = { path = "../../rosetta-api/ledger_canister" }
maplit = "1.0.2"
pretty-bytes = "0.2.2"
prost = "0.10.0"
rand = "0.8.4"
rand_core = "0.6.2"

# Dependencies required to compile the tests.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
assert_matches = "1.3.0"
canister-test = { path = "../../rust_canisters/canister_test" }
ic-base-types={path="../../types/base_types"}
ic-canister-client = { path = "../../canister_client" }
ic-crypto = { path = "../../crypto" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-sns-governance = { path = "../governance" }
ic-sns-root = { path = "../root" }
ic-sns-test-utils = { path = "../test_utils" }
ic-types = { path = "../../types/types" }
itertools = "0.10.3"
lazy_static = "1.4.0"
on_wire = { path = "../../rust_canisters/on_wire" }
tokio = { version = "1.17.0", features = ["time"] }
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }
