[package]
name = "ic-sns-integration-tests"
version = "0.8.0"
edition = "2018"

[[bin]]
name = "sns-test-dapp-canister"
path = "test_canisters/test_dapp_canister.rs"

# Dependencies required to compile the test canisters.
[dependencies]
candid = "0.7.4"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_json = { path = "../../rust_canisters/dfn_json" }
ic-base-types = { path = "../../types/base_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ledger-canister = { path = "../../rosetta-api/ledger_canister" }
maplit = "1.0.2"

# Dependencies required to compile the tests.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.17.0", features = ["time"] }
assert_matches = "1.3.0"
canister-test = { path = "../../rust_canisters/canister_test" }
ic-canister-client = { path = "../../canister_client" }
ic-base-types={path="../../types/base_types"}
ic-crypto = { path = "../../crypto" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
ic-nns-test-keys = { path = "../../nns/test_keys" }
ic-sns-governance = { path = "../governance" }
ic-sns-root = { path = "../root" }
ic-sns-test-utils = { path = "../test_utils" }
ic-types = { path = "../../types/types" }
on_wire = { path = "../../rust_canisters/on_wire" }
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }
