[package]
name = "ic-pprof"
version = "0.8.0"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
pprof = { version = "0.5.0", default-features = false, features = ["flamegraph", "protobuf"] }
prost = "0.8.0"
regex = "1.3.9"
thiserror = "1.0"
tokio = { version = "1.9.0", features = [ "full" ] }
