[package]
name = "ic-scenario-tests"
version = "0.8.0"
edition = "2018"
autotests = false

[dependencies]
candid = "0.7.4"
canister-test = { path = "../rust_canisters/canister_test" }
chrono = "0.4.19"
colored = "2.0.0"
crossbeam-channel = "0.5.0"
dfn_candid = { path = "../rust_canisters/dfn_candid" }
dfn_core = { path = "../rust_canisters/dfn_core" }
dfn_json = { path = "../rust_canisters/dfn_json" }
ed25519-dalek = "1.0.1"
futures = "0.3.6"
hex = "0.4.2"
ic-base-types = { path = "../types/base_types"}
ic-canister-client = { path = "../canister_client" }
ic-config = { path = "../config" }
ic-crypto = { path = "../crypto" }
ic-crypto-sha = { path = "../crypto/sha" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-nns-common = { path = "../nns/common" }
ic-nns-constants = { path = "../nns/constants" }
ic-nns-governance = { path = "../nns/governance" }
ic-nns-test-utils = { path = "../nns/test_utils" }
ic-prep = { path = "../prep" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-common = { path = "../registry/common" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-registry-transport = { path = "../registry/transport" }
ic-release = { path = "../release" }
ic-state-manager = { path = "../state_manager" }
ic-test-identity = { path = "../test_utilities/identity" }
ic-test-utilities = { path = "../test_utilities" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
lazy_static = "1.4.0"
log_analyzer = { path = "../log_analyzer" }
nix = "0.23.0"
on_wire = { path = "../rust_canisters/on_wire" }
phantom_newtype = { path = "../phantom_newtype" }
process_manager = { path = "../process_manager" }
prost = "0.9.0"
rand = "0.7.3"
rand_chacha = "0.2.2"
rand_core = "0.5.1"
registry-canister = { path = "../registry/canister" }
reqwest = "0.11.1"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_json = "1.0"
structopt = "0.3"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
slog-async = "2.5.0"
slog-term = "2.6.0"
tempfile = "3.1.0"
tester = "0.7.0"
tokio = {version = "1.15.0", features = ["full"]}
url = "2.1.1"
xnet-test = { path = "../rust_canisters/xnet_test" }
ic-nns-handler-root = {path="../nns/handlers/root"}
ic-crypto-internal-types = { path = "../crypto/internal/crypto_lib/types" }
ic-crypto-utils-basic-sig = { path = "../crypto/utils/basic_sig" }
ic-crypto-utils-threshold-sig = { path = "../crypto/utils/threshold_sig" }

[[bin]]
name = "e2e-test-driver"
path = "src/main.rs"
