[package]
name = "ic-execution-environment"
version = "0.8.0"
edition = "2018"

[dependencies]
candid = "0.6.15"
ic-base-types = { path = "../types/base_types" }
ic-config = { path = "../config" }
ic-cow-state = { path = "../cow_state" }
ic-crypto = { path = "../crypto" }
ic-crypto-sha256 = { path = "../crypto/sha256" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-embedders = { path = "../embedders" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-registry-client = { path = "../registry/client" }
ic-registry-common = { path = "../registry/common" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-state-layout = { path = "../state_layout" }
ic-sys = { path = "../sys" }
ic-system-api = { path = "../system_api" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-wasm-utils = { path = "../wasm_utils" }
nix = "0.20.0"
num-traits = "0.2.12"
num-rational = "0.2.2"
scoped_threadpool = "0.1.*"
prometheus = { version = "0.12.0", features = [ "process" ] }
rand = "0.7.3"
reqwest = { version = "0.11.1", features = [ "native-tls" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
serde_cbor = "0.11.1"
serde_json = "1.0.40"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
strum = "0.18.0"

[dev-dependencies]
assert_matches = "1.3.0"
ic-test-utilities = { path = "../test_utilities" }
ic-wasm-types = { path = "../types/wasm_types" }
lazy_static = "1.4.0"
maplit = "1.0.2"
mockall = "0.7.2"
proptest = "0.9.4"
tempfile = "3.1.0"
wabt = "0.10.0"

[build-dependencies]
escargot = "0.5"

[[test]]
name = "wasmtime-tests"
path = "testgrid/wasmtime_tests.rs"

[[test]]
name = "cow-wasmtime-tests"
path = "testgrid/cow_wasmtime_tests.rs"

[features]
default = []
sigsegv_handler_debug = []
