[package]
name = "unaffected"
version = "0.1.0"
authors = ["The Internet Computer Project Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-types = "0.2.1"
