[package]
name = "ic-http-handler"
version = "0.8.0"
edition = "2018"

[dependencies]
askama = "0.10.5"
futures-util = "0.3.13"
hex = "0.4.2"
http = "0.2.5"
flate2 = "1.0.20"
futures = "0.3.13"
hyper = { version = "0.14.5", features = ["full"] }
ic-base-thread = { path = "../base/thread" }
ic-config = { path = "../config" }
ic-crypto = { path = "../crypto" }
ic-crypto-tls-interfaces = { path = "../crypto/tls_interfaces" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-pprof = { path = "../monitoring/pprof" }
ic-registry-client = { path = "../registry/client" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-validator = { path = "../validator" }
prometheus = { version = "0.12.0", features = [ "process" ] }
prost = "0.9.0"
rand = "0.8.3"
reqwest = { version = "0.11.1", features = [ "native-tls", "blocking" ] }
serde = "1.0.99"
serde_cbor = "0.11.1"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
tar = "0.4.30"
tempfile = "3.1.0"
tokio = { version = "1.9.0", features = [ "full" ] }
tower =  { version = "0.4.8", features = ["load-shed", "limit"] }
tower-util = "0.3.1"
url = "2.1.1"

[dev-dependencies]
bytes = "1.0.1"
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"
pretty_assertions = "0.7.1"
proptest = "1.0.0"

[features]
malicious_code = ["ic-validator/malicious_code"]
