[package]
name = "ic-sns-cli"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "sns"
path = "src/main.rs"

[dependencies]
candid = "0.7.4"
clap = { version = "3.1.6", features = ["derive"] }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-nervous-system-common = {path = "../../nervous_system/common"}
ic-protobuf = { path = "../../protobuf" }
ic-sns-test-utils = { path = "../test_utils" }
ic-sns-governance = { path = "../governance" }
ic-sns-init = { path = "../init" }
ic-sns-root = { path = "../root" }
ledger-canister = { path = "../../rosetta-api/ledger_canister" }
maplit = "1.0.2"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"
rand = "0.7.3"
rand_core = "0.5.1"
bytes = "1.0.1"
hex = "0.4.3"
url = "2.2.0"

