[package]
name = "ic-crypto-test-utils-threshold-sigs"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-config = { path = "../../../config" }
ic-crypto = { path = "../.." }
ic-crypto-internal-types = { path = "../../internal/crypto_lib/types" }
ic-interfaces = { path = "../../../interfaces" }
ic-registry-client-fake = { path = "../../../registry/fake" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-proto-data-provider = { path = "../../../registry/proto_data_provider" }
ic-types = { path = "../../../types/types" }
rand = "0.7.3"
