[package]
name = "ic-regedit"
version = "0.8.0"
edition = "2018"

[dependencies]
anyhow = "1.0.31"
structopt = "0.3.21"
ic-crypto-sha = {path = "../../crypto/sha/"}
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../client" }
ic-registry-client-helpers = { path = "../helpers" }
ic-registry-common = { path = "../common" }
ic-registry-keys = { path = "../keys" }
ic-registry-subnet-type = { path = "../subnet_type" }
ic-base-types = { path = "../../types/base_types" }
prost = "0.9.0"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.54"
thiserror = "1.0"
tokio = { version = "1.15.0" }
url = { version = "2.1.1", features = ["serde"] }

[dev-dependencies]
ic-prep = { path = "../../prep" }
ic-registry-provisional-whitelist = { path = "../provisional_whitelist" }
tempfile = "3.1.0"

[[bin]]
name = "ic-regedit"
path = "src/main.rs"
