[package]
name = "ic-registry-local-store"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-interfaces = { path = "../../interfaces" }
ic-registry-common-proto = { path = "../proto" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils" }
bytes = "1.0.1"
prost = "0.10.4"

[dev-dependencies]
rand = "0.7.3"
tempfile = "3.0"
