[package]
name = "ic-sns-root"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "sns-root-canister"
path = "canister/canister.rs"

[dependencies]
candid = "0.7.4"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
