[package]
name = "ic-sns-root"
version = "0.8.0"
edition = "2021"

[[bin]]
name = "sns-root-canister"
path = "canister/canister.rs"

[dependencies]
candid = "0.7.4"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-base-types = { path = "../../types/base_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-root = { path = "../../nervous_system/root" }
prost = "0.9.0"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
ic-base-types = { path = "../../types/base_types" }
prost-build = "0.9.0"
