[package]
name = "ic-nervous-system-root"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.7.5"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-base-types = { path = "../../types/base_types" }
ic-cdk = { version = "0.3.1", default-features = false }
ic-crypto-sha = { path = "../../crypto/sha/" }
ic-nervous-system-common = { path="../common" }
ic-ic00-types = { path = "../../types/ic00_types" }
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"
