[package]
name = "ic-registry-keys"
version = "0.8.0"
edition = "2018"

[dependencies]
candid = "0.7.4"
ic-base-types = { path = "../../types/base_types" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-types = { path = "../../types/types" }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand = "0.7.3"
