[package]
name = "ic-starter"
version = "0.8.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
ic-config = { path = "../config" }
ic-crypto = { path = "../crypto" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-prep = { path = "../prep" }
ic-protobuf = { path = "../protobuf" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-registry-client = { path = "../registry/client" }
ic-registry-common = { path = "../registry/common" }
ic-types = { path = "../types/types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.40"
slog = { version = "2.5.2", features = [
    "nested-values",
    "max_level_trace",
    "release_max_level_debug",
] }
slog-term = "2.6.0"
structopt = "0.3"
tempfile = "3.1.0"
url = "2.1.1"

[[bin]]
name = "ic-starter"
path = "src/main.rs"
