[package]
name = "ic-xnet-hyper"
version = "0.8.0"
edition = "2018"

[dependencies]
hyper = { version = "0.14.18" , features = ["full", "tcp"] }
ic-crypto-tls-interfaces = { path = "../../crypto/tls_interfaces" }
ic-interfaces = { path = "../../interfaces" }
ic-xnet-uri = { path = "../uri" }
socket2 = { version = "0.3.19", features = ["reuseport"] }
tokio = { version = "1.15.0", features = ["full"] }