[package]
name = "ic-canister-http-adapter-service"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-protobuf = { path = "../../protobuf" }
tonic = "0.6.2"

[build-dependencies]
prost-build = "0.9.0"
tonic-build = "0.6.2"

