[package]
name = "ic-sns-wasm"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "sns-wasm-canister"
path = "canister/canister.rs"

[lib]
path = "src/lib.rs"

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

async-trait = "0.1.42"
candid = "0.7.4"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = {path = "../../crypto/sha/"}
ic-ic00-types = {path = "../../types/ic00_types"}
ic-types = { path = "../../types/types"}
serde = { version = "1.0", features = ["derive"] }
prost = "0.10.4"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
ic-protobuf = { path = "../../protobuf" }
registry-canister = { path = "../../registry/canister" }
ic-registry-keys = { path = "../../registry/keys" }
ic-interfaces = { path = "../../interfaces" }

[dev-dependencies]
ic-sns-wasm-proto-generator = { path = "./proto_generator" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
tempfile = "3.1.0"
tokio = { version = "1.15.0", features = ["full"] }
ic-state-machine-tests = { path = "../../state_machine_tests" }
canister-test = { path = "../../rust_canisters/canister_test" }
ic-nns-test-utils = {path="../../nns/test_utils"}
