[package]
name = "ic-xnet-payload-builder"
version = "0.8.0"
edition = "2018"

[dependencies]
async-trait = "0.1.31"
hyper = { version = "0.14.18" , features = ["full", "tcp"] }
ic-base-types = { path = "../../types/base_types" }
ic-canonical-state = { path = "../../canonical_state" }
ic-constants = { path = "../../constants" }
ic-crypto-tls-interfaces = { path = "../../crypto/tls_interfaces" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-interfaces = { path = "../../interfaces" }
ic-interfaces-state-manager = { path = "../../interfaces/state_manager" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-subnet-type = { path = "../../registry/subnet_type" }
ic-replicated-state = { path = "../../replicated_state" }
ic-types = { path = "../../types/types" }
ic-xnet-hyper = { path = "../hyper" }
ic-xnet-uri = { path = "../uri" }
prometheus = { version = "0.12.0", features = [ "process" ] }
rand = "0.7.3"
rand_chacha = "0.2.2"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
tokio = { version = "1.15.0", features = ["full"] }

[dev-dependencies]
assert_matches = "1.3.0"
ic-config = { path = "../../config" }
ic-registry-client-fake = { path = "../../registry/fake" }
ic-registry-proto-data-provider = { path = "../../registry/proto_data_provider" }
ic-state-manager = { path = "../../state_manager" }
ic-test-utilities = { path = "../../test_utilities" }
ic-test-utilities-registry = { path = "../../test_utilities/registry" }
maplit = "1.0.2"
mockall = "0.7.2"
nix = "0.23.0"
proptest = "0.9.4"
reqwest = "0.11.1"
tempfile = "3.1.0"
tiny_http = "0.10.0"
url = "2.1.1"