[package]
name = "ic-system-api"
version = "0.8.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-base-types = { path = "../types/base_types" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
ic-logger = { path = "../monitoring/logger" }
serde = { version = "1.0.99", features = ["derive"] }
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }

[dev-dependencies]
ic-test-utilities = { path = "../test_utilities" }
lazy_static = "1.4.0"
maplit = "1.0.2"
