bazel-test:
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline-autorun-on-trigger
  stage: test
  script:
    - |
      set -euo pipefail

      bazel --version
      bazel build :all --remote_cache=grpc://10.117.26.74:8980

      bazel build --spawn_strategy=standalone --remote_cache=grpc://10.117.26.74:8980 //ic-os/guestos:disk.img.tar
