bazel-test:
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline-autorun-on-trigger
  stage: test
  artifacts:
    paths:
      - bazel-build-log*.json
  script:
    - |
      set -euo pipefail

      bazel --version
      bazel build :all --remote_cache=grpc://10.117.26.74:8980 --execution_log_json_file=bazel-build-log-all.json

      bazel build --spawn_strategy=standalone --remote_cache=grpc://10.117.26.74:8980 //ic-os/guestos:disk.img.tar --execution_log_json_file=bazel-build-log-guestos.json
