.bazel-run:
  # Run in ZH since BuildFarm is in ZH
  tags:
    - dfinity
    - docker
    - ubuntu
    - zh
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline-autorun-on-trigger
  stage: test
  artifacts:
    paths:
      - bazel-build-log*.json
  before_script:
    - !reference [before_script]
    - set -euo pipefail
    - bazel --version

bazel-test-all:
  extends:
    - .bazel-run
  stage: test
  script:
    - bazel test --config ci ...

# TODO: convert buildifier.check to a _test rule and remove this job.
bazel-buildifier-check:
  extends:
    - .bazel-run
  stage: test
  script:
    - bazel run --config ci //:buildifier.check || (echo "Please auto-format your changes with \`bazel run //:buildifier\`" && exit 1)
