.bazel-run:
  # Run in ZH since BuildFarm is in ZH
  tags:
    - dfinity
    - docker
    - ubuntu
    - zh
  extends:
    - .ubuntu-nix-docker
    - .rules-parent-pipeline-autorun-on-trigger
  stage: test
  artifacts:
    paths:
      - bazel-build-log*.json
  before_script:
    - !reference [before_script]
    - set -euo pipefail
    - bazel --version

bazel-test-all:
  extends:
    - .bazel-run
  stage: test
  script:
    - bazel test --config ci ...
