---
- hosts: localhost
  any_errors_fatal: yes
  gather_facts: false
  become: false

  vars_prompt:
    - name: "yes_i_confirm"
      prompt: "REALLY DEPLOY THE NEW MONITORING CONFIGURATION? [YES/no]"
      default: "yes"
      private: no

  tasks:
    - name: check Confirmation
      fail: msg="Playbook run confirmation failed"
      when: yes_i_confirm != "yes"
    - shell: git branch --show-current
      register: git_branch

- hosts: prometheus
  gather_facts: false
  become: false

  vars_files:
    - "{{ inventory_file | dirname }}/versions.json"
    - "config/common.yml"

  roles:
    - role: ic_p8s_network_update
