[package]
name = "ic-wasm-utils"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-wasm-types = { path = "../types/wasm_types" }
parity-wasm = { version = "0.40.0", default-features = true }
wasmtime = "0.22.0"

[dev-dependencies]
assert_matches = "1.3.0"
pretty_assertions = "0.6.1"
wabt = "0.10.0"

[[bin]]
name = "instrument-wasm"
path = "src/instrument_wasm.rs"
