[package]
name = "ic-wasm-utils"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-wasm-types = { path = "../types/wasm_types" }
parity-wasm = { version = "0.42.2", features = [ "std", "multi_value", "bulk" ] }
wasmtime = { version = "0.29.0", default_features = false, features = ['async', 'parallel-compilation', 'posix-signals-on-macos']}
serde = { version = "1.0.99", features = [ "derive" ] }
ic-config = { path = "../config" }
ic-sys = { path = "../sys" }

[dev-dependencies]
assert_matches = "1.3.0"
insta = "1.8.0"
pretty_assertions = "0.6.1"
wabt = "0.10.0"

[[bin]]
name = "instrument-wasm"
path = "src/instrument_wasm.rs"
