[package]
name = "ic-sns-init"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.57"
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = { path = "../../crypto/sha" }
ic-nervous-system-common = { path = "../../nervous_system/common"}
ic-sns-governance = { path = "../governance" }
ic-sns-root = { path = "../root" }
ledger-canister = { path = "../../rosetta-api/ledger_canister" }
maplit = "1.0.2"
num = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.79"

[dev-dependencies]
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }
assert_approx_eq = "1.1.0"