[package]
name = "ic-canister-sandbox-replica-controller"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-canister-sandbox-common = { path = "../common" }
ic-canister-sandbox-backend-lib = { path = "../backend_lib" }
ic-embedders = { path = "../../embedders" }
ic-interfaces = { path = "../../interfaces" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-config = { path = "../../config" }
ic-replicated-state = { path = "../../replicated_state" }
ic-sys = { path = "../../sys" }
ic-system-api = { path = "../../system_api" }
ic-types = { path = "../../types/types" }
ic-wasm-types = { path = "../../types/wasm_types" }
lazy_static = "1.4.0"
serde_json = "1.0.54"
libc = "0.2.119"
nix = "0.23.0"
once_cell = "1.8"
prometheus = { version = "0.12.0", features = [ "process" ] }
regex = "1.5.4"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
which = "4.2.2"

[dev-dependencies]
ic-config = { path = "../../config" }
ic-test-utilities = { path = "../../test_utilities" }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
tempfile = "3.1.0"
wabt = { git = "https://github.com/dfinity-lab/wabt-rs", tag = "0.10.0-dfinity" }

[features]
sigsegv_handler_checksum = []
