[package]
name = "ic-nns-handler-root"
version = "0.8.0"
edition = "2018"

[[bin]]
name = "root-canister"
path = "canister/canister.rs"

[[bin]]
name = "upgrade-test-canister"
path = "test_canisters/upgrade_test_canister.rs"

[lib]
path = "src/lib.rs"

[dependencies]
candid = "0.7.4"
futures = "0.3.8"
serde = { version = "1.0.99", features = ["derive", "rc"] }
serde_bytes = "0.11"
ic-nns-common ={path="../../common"}
ic-nns-constants ={path="../../constants"}
ic-nns-governance = { path = "../../governance"}
ic-ic00-types = {path="../../../types/ic00_types"}
ic-base-types = {path="../../../types/base_types"}
dfn_candid = {path="../../../rust_canisters/dfn_candid"}
dfn_core = { path = "../../../rust_canisters/dfn_core" }
dfn_macro = { path = "../../../rust_canisters/dfn_macro" }
on_wire = { path = "../../../rust_canisters/on_wire"}
ic-protobuf = { path = "../../../protobuf" }
prost = "0.7.0"
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-transport = { path = "../../../registry/transport" }
ic-cdk = { version = "0.3.1", default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
ic-nns-constants ={path="../../constants"}
ic-types = { path = "../../../types/types" }
ic-test-utilities = {path="../../../test_utilities"}
on_wire = { path = "../../../rust_canisters/on_wire" }
assert_matches = "1.3.0"
hex = "0.4.2"
lazy_static = "1.4.0"
ic-crypto-sha = { path = "../../../crypto/sha" }
registry-canister = { path = "../../../registry/canister" }

[build-dependencies]
ic-base-types = {path="../../../types/base_types"}
prost-build = "0.7.0"
