[package]
name = "ic-nns-handler-root"
version = "0.8.0"
edition = "2018"

[[bin]]
name = "root-canister"
path = "canister/canister.rs"

[[bin]]
name = "upgrade-test-canister"
path = "test_canisters/upgrade_test_canister.rs"

[lib]
path = "src/lib.rs"

[dependencies]
candid = "0.7.5"
dfn_candid = {path="../../../rust_canisters/dfn_candid"}
dfn_core = { path = "../../../rust_canisters/dfn_core" }
dfn_macro = { path = "../../../rust_canisters/dfn_macro" }
futures = "0.3.8"
ic-base-types = {path="../../../types/base_types"}
ic-cdk = { version = "0.3.1", default-features = false }
ic-crypto-sha = {path = "../../../crypto/sha/"}
ic-ic00-types = {path="../../../types/ic00_types"}
ic-nervous-system-root = { path = "../../../nervous_system/root" }
ic-nns-common ={path="../../common"}
ic-nns-constants ={path="../../constants"}
ic-nns-governance = { path = "../../governance"}
ic-protobuf = { path = "../../../protobuf" }
ic-registry-keys = { path = "../../../registry/keys" }
ic-registry-transport = { path = "../../../registry/transport" }
ic-registry-routing-table = { path = "../../../registry/routing_table" }
on_wire = { path = "../../../rust_canisters/on_wire"}
prost = "0.9.0"
serde = { version = "1.0.99", features = ["derive"] }
serde_bytes = "0.11"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
canister-test = { path = "../../../rust_canisters/canister_test" }
ic-nns-constants ={path="../../constants"}
ic-nns-test-utils = { path = "../../../nns/test_utils" }
ic-types = { path = "../../../types/types" }
ic-test-utilities = {path="../../../test_utilities"}
on_wire = { path = "../../../rust_canisters/on_wire" }
assert_matches = "1.3.0"
hex = "0.4.2"
lazy_static = "1.4.0"
registry-canister = { path = "../../../registry/canister" }

[build-dependencies]
ic-base-types = {path="../../../types/base_types"}
prost-build = "0.9.0"
