[package]
name = "tecdsa"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ic-crypto-sha = { path = "../../../../sha" }
k256 = { version = "0.9.5", features = ["arithmetic"] }
p256 = { version = "0.9.0", features = ["arithmetic"] }
rand_core = "0.5"
rand_chacha = "0.2.2"
sha2 = "0.9"

[dev-dependencies]
hex = "0.4"
rand = "0.7"
