---

#- name: Retrieve host vars
#  debug:
#    var: "{{ index }} - {{ item }}"
#  tags: [ "boundary_node_vm" ]
#
#- name: Retrieve host vars
#  debug:
#    var: inventory_hostname
#  tags: [ "boundary_node_vm" ]

- name: copy media.img to remote
  copy:
    # copy the media image built for the node, or fallback to the generic 'media.img'
    src: "{{ lookup('first_found', ['{{ ic_media_path }}/{{ item }}.img', '{{ ic_media_path }}/media.img']) }}"
    dest: "/var/local/ic/media/{{ ic_deployment_name }}/{{ ic_git_revision }}/{{ item }}.img"
    mode: "0644"
    owner: root
    group: root
  loop: "{{ hostvars[inventory_hostname].ic_guests | default([]) }}"
  tags: [ "ic_guest" ]

- name: copy new boundary node VM media.img to remote
  copy:
    # copy the media image built for the new boundary node
    src: "{{ bn_media_path }}/{{ item }}.img"
    dest: "/var/local/ic/media/{{ ic_deployment_name }}/{{ ic_git_revision }}/boundary/"
    mode: "0644"
    owner: root
    group: root
  loop: "{{ hostvars[inventory_hostname].groups.boundary | default([]) }}"
  tags: [ "boundary_node_vm" ]

- name: copy single boundary node VM media.img to remote
  copy:
    # copy the media image built for the new boundary node
    src: "{{ bn_media_path }}/{{ item }}.img"
    dest: "/var/lib/libvirt/media/{{ item }}.img"
    mode: "0644"
    owner: root
    group: root
  loop: "{{ hostvars[inventory_hostname].groups.boundary | default([]) }}"
  loop_control:
    index_var: index
  tags: [ "boundary_node_vm" ]

