[package]
name = "ic-messaging"
version = "0.8.0"
edition = "2018"

[dependencies]
futures = "0.3.6"
async-trait = "0.1.31"
crossbeam-channel = "0.5.0"
hyper = { version = "0.14.16" , features = ["full", "tcp", ] }
ic-base-types = { path = "../types/base_types" }
ic-canonical-state = { path = "../canonical_state" }
ic-config = { path = "../config" }
ic-crypto = { path = "../crypto" }
ic-crypto-tls-interfaces = { path = "../crypto/tls_interfaces" }
ic-crypto-tree-hash = { path = "../crypto/tree_hash" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-common = { path = "../registry/common" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-provisional-whitelist = { path = "../registry/provisional_whitelist" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-registry-subnet-features = { path = "../registry/subnet_features" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
lazy_static = "1.4.0"
prometheus = { version = "0.12.0", features = [ "process" ] }
rand = "0.7.3"
rand_chacha = "0.2.2"
serde = { version = "1.0.99", features = [ "derive" ] }
serde_json = "1.0.40"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
socket2 = { version = "0.3.19", features = ["reuseport"] }
tokio = { version = "1.15.0", features = ["full"] }
url = "2.1.1"

[dev-dependencies]
assert_matches = "1.3.0"
bytes = "1.0.1"
ic-state-manager = { path = "../state_manager" }
ic-test-utilities = { path = "../test_utilities" }
maplit = "1.0.2"
mockall = "0.7.2"
nix = "0.23.0"
proptest = "0.9.4"
prost = "0.9.0"
reqwest = "0.11.1"
tempfile = "3.1.0"
tiny_http = "0.10.0"
