[package]
name = "ic-cycles-account-manager"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-base-types = { path = "../types/base_types" }
ic-config = { path = "../config" }
ic-ic00-types = { path = "../types/ic00_types" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-nns-constants = { path = "../nns/constants" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-replicated-state = { path = "../replicated_state" }
ic-types = { path = "../types/types" }
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = ["derive"] }
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }

[dev-dependencies]
ic-test-utilities = { path = "../test_utilities" }
ic-wasm-types = { path = "../types/wasm_types" }
