[package]
name = "ic-p2p"
version = "0.8.0"
edition = "2018"

[dependencies]
async-trait = "0.1.36"
bincode = "1.2.1"
crossbeam-channel = "0.5.0"
enum-map = "0.6.2"
futures = "0.3.10"
rand = "0.7.3"
ic-artifact-manager = { path = "../artifact_manager" }
ic-base-thread = { path = "../base/thread" }
ic-config = { path = "../config" }
ic-crypto = { path = "../crypto" }
ic-cycles-account-manager = { path = "../cycles_account_manager" }
ic-interfaces = { path = "../interfaces" }
ic-types = { path = "../types/types" }
ic-protobuf = { path = "../protobuf" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-registry-client = { path = "../registry/client" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
linked-hash-map = "0.5.3"
lru = { version = "0.7.1", default-features = false }
phantom_newtype = { path = "../phantom_newtype" }
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = [ "derive" ] }
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
strum = "0.23.0"
strum_macros = "0.23.0"
tokio = { version = "1.15.0", features = ["full"] }
tower-service = "0.3.1"

[dev-dependencies]
ic-consensus-message = { path = "../consensus/message" }
ic-execution-environment = { path = "../execution_environment" }
ic-registry-common = { path = "../registry/common" }
ic-test-utilities = { path = "../test_utilities" }
ic-registry-subnet-type = { path = "../registry/subnet_type" }
ic-logger = { path = "../monitoring/logger" }
ic-replica-setup-ic-network = { path = "../replica/setup_ic_network" }
mockall = "0.7.2"
tempfile = "3.1.0"
proptest = "0.9.4"

[features]
malicious_code = ["ic-artifact-manager/malicious_code"]
