[package]
name = "ic-base-types"
version = "0.8.0"
edition = "2018"

[dependencies]
base32 = "0.4.0"
bytes = "1.0.1"
byte-unit = "4.0.14"
candid = "0.7.14"
crc32fast = "1.2.0"
ic-crypto-sha = { path = "../../crypto/sha" }
ic-protobuf = { path = "../../protobuf" }
phantom_newtype = { path = "../../phantom_newtype" }
prost = "0.10.4"
serde = { version = "1.0.99", features = ["derive"] }
strum = "0.23.0"
strum_macros = "0.23.0"
comparable = { version = "0.5", features = ["derive"] }

[dev-dependencies]
assert_matches = "1.3.0"
ic-base-types-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
proptest = "0.9.4"
proptest-derive = "0.1.0"
serde_cbor = "0.11.1"
tempfile = "3.1.0"

[features]
test = []
