[package]
name = "ic-registry-nns-data-provider"
version = "0.8.0"
edition = "2018"

[dependencies]
ic-canister-client = { path = "../../canister_client" }
ic-certified-vars = { path = "../../certified_vars" }
ic-crypto-tree-hash = { path = "../../crypto/tree_hash" }
ic-crypto-utils-threshold-sig = { path = "../../crypto/utils/threshold_sig" }
ic-interfaces = { path = "../../interfaces" }
ic-nns-constants = { path = "../../nns/constants" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-common-proto = { path = "../proto" }
ic-registry-transport = { path = "../transport" }
ic-types = { path = "../../types/types" }
ic-utils = { path = "../../utils" }
bytes = "1.0.1"
chrono = "0.4.19"
hyper = "0.14.18"
hyper-tls = "0.5.0"
prost = "0.10.4"
rand = "0.7.3"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
tokio = { version = "1.15.0", features = ["full"] }
tree-deserializer = { path = "../../tree_deserializer" }
lazy_static = "1.4.0"
url = { version = "2.1.1", features = ["serde"] }
tempfile = "3.0"

[dev-dependencies]
ic-crypto = { path = "../../crypto" }
ic-certified-vars-test-utils = { path = "../../certified_vars/test-utils" }
leb128 = "0.2.4"
