[package]
name = "ic-nns-governance"
version = "0.8.0"
edition = "2018"

[[bin]]
name = "governance-canister"
path = "canister/canister.rs"

[lib]
path = "src/lib.rs"

[[test]]
name = "governance-test"
path = "tests/governance.rs"

[[test]]
name = "governance-interleaving-test"
path = "tests/interleaving_tests.rs"

[[bench]]
name = "scale"
harness = false

[dependencies]
# This MUST be kept in sync with build-info-build in the [build-dependencies] section!
build-info = { version = "0.0.26", default-features = false, features = [] }

anyhow = "1.0.57"
async-trait = "0.1.42"
candid = "0.7.4"
comparable = { version = "0.5", features = ["derive"] }
cycles-minting-canister = { path = "../cmc" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_http_metrics = { path = "../../rust_canisters/dfn_http_metrics" }
dfn_protobuf = { path = "../../rust_canisters/dfn_protobuf" }
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = {path = "../../crypto/sha/"}
ic-metrics-encoder = { path = "../../monitoring/metrics_encoder" }
ic-nervous-system-common = { path = "../../nervous_system/common" }
ic-nervous-system-common-build-metadata = { path = "../../nervous_system/common/build_metadata" }
ic-nns-common = { path = "../common" }
ic-nns-constants = { path = "../constants" }
ic-protobuf = { path = "../../protobuf" }
ledger-canister = { path = "../../rosetta-api/ledger_canister" }
num = "0.4.0"
on_wire = { path = "../../rust_canisters/on_wire" }
prost = "0.10.4"
serde = { version = "1.0", features = ["derive"] }
rand = "0.7.3"
rand_core = "0.5.1"
registry-canister = { path = "../../registry/canister" }
strum_macros = "0.23.0"
strum = "0.23.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
csv = "1.1"
ic-nervous-system-common-test-keys = { path = "../../nervous_system/common/test_keys" }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
assert_matches = "1.3.0"
ic-types = { path = "../../types/types" }
maplit = "1.0.2"

[build-dependencies]
# This MUST be kept in sync with build-info in the [dependencies] section!
build-info-build = { version="0.0.26", default-features = false, features = [] }

[dev-dependencies]
criterion = "0.3"
futures = "0.3.13"
ic-base-types = { path = "../../types/base_types", features = ["test"] }
ic-config = { path = "../../config" }
ic-nns-common = { path = "../common", features = ["test"] }
ic-nns-governance-protobuf-generator = { path = "./protobuf_generator" }
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
ledger-canister = { path = "../../rosetta-api/ledger_canister", features = ["test"] }
pretty_assertions = "1.0"
proptest = "1.0"
tempfile = "3.1.0"
tokio = { version = "1.9.0", features = [ "full" ] }
tokio-test = "0.4.2"

[features]
test = ["ic-base-types/test", "ic-nns-common/test", "ledger-canister/test"]
