[package]
name = "vsock_agent"
version = "0.8.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(target_os = "linux")'.dependencies]
nix = "0.23.0"
libc = "0.2.88"
vsock = "0.2.6"
rand = "0.8.3"
sha2 = "0.9.3"
serde_json = "1.0.64"
clap = { version = "3.1.6", features = ["derive"] }

[lib]
name = "vsock_agent"
