[package]
name = "ic-async-utils"
version = "0.8.0"
edition = "2018"

[dependencies]
async-stream = "0.3.2"
futures = "0.3.13"
prometheus = { version = "0.12.0", features = [ "process" ] }
tokio = { version = "1.15.0", features = ["full"] }
tonic = "0.6.2"
slog = "2.5.2"

