deny_node_socket_addrs: ""
client_acls: []
dns_aliases: []
generate_upstream_declarations: True
keys_zone_size: 10m
cache_size: 100m
nns_public_key: ""
custom_domains: []
icx_proxy_debug: False
icx_proxy_trace: False
control_plane_metrics_port: 0
prober_metrics_port: 0
service_worker_domain: ""
redirect_to_dashboard_regex: ""
journalbeat_version: "7.14.0"
journalbeat_hosts: "elasticsearch.testnet.dfinity.systems:443"
mainnet_service_worker: False
