[package]
name = "ic-btc-adapter-client"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.27.1"
ic-btc-service = { path = "../service" }
ic-btc-types-internal = { path = "../types/internal" }
ic-interfaces-bitcoin-adapter-client = { path = "../../interfaces/bitcoin_adapter_client" }
ic-logger = { path = "../../monitoring/logger" }
serde = { version = "1.0.99", features = [ "derive" ] }
serde_bytes = "0.11.5"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
tokio = { version = "1.15.0", features = ["full"] }
tonic = "0.6.2"
tower = { version = "0.4.11", features = ["util"] }

