[package]
name = "orchestrator"
version = "0.8.0"
edition = "2018"

[dependencies]
base64 = "0.13.0"
candid = "0.7.4"
exec = "0.3.1"
futures = "0.3.5"
hex = "0.4.2"
http = "0.2.1"
hyper = "0.14.16"
hyper-tls = "0.5.0"
ic-base-thread = { path = "../base/thread" }
ic-base-server = { path = "../base/server" }
ic-canister-client = { path = "../canister_client" }
ic-config = { path = "../config" }
ic-consensus-message = { path = "../consensus/message" }
ic-consensus = { path = "../consensus" }
ic-crypto = { path = "../crypto" }
ic-crypto-tls-interfaces = { path = "../crypto/tls_interfaces" }
ic-crypto-utils-threshold-sig = { path = "../crypto/utils/threshold_sig" }
ic-crypto-sha = { path = "../crypto/sha" }
ic-http-utils = { path = "../http_utils" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-metrics-exporter = { path = "../monitoring/metrics_exporter" }
ic-nns-constants = { path = "../nns/constants" }
ic-protobuf = { path = "../protobuf" }
ic-registry-client = { path = "../registry/client" }
ic-registry-common = { path = "../registry/common" }
ic-registry-keys = { path = "../registry/keys" }
ic-registry-routing-table = { path = "../registry/routing_table" }
ic-release = { path = "../release" }
ic-sys = { path = "../sys" }
ic-types = { path = "../types/types" }
ic-utils = { path = "../utils" }
lazy_static = "1.4.0"
nix = "0.23.0"
prometheus = { version = "0.12.0", features = [ "process" ] }
rand = "0.7.3"
prost = "0.9.0"
registry-canister = { path = "../registry/canister" }
serde = { version = "1.0.99", features = [ "derive" ] }
serde_cbor = "0.11.1"
signal-hook = "0.1"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
slog-async = { version = "2.5", features = ["nested-values"] }
slog-term = "2.6.0"
structopt = "0.3"
tar = "0.4.38"
tempfile = "3.1.0"
tokio = { version = "1.15.0", features = ["full"] }
url = "2.1.1"

[dev-dependencies]
assert_cmd = "0.12"
ic-test-utilities = { path = "../test_utilities" }
wait-timeout = "0.2.0"
