[package]
name = "ledger-canister"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
description = "Like an accountant, but on the blockchain!"
edition = "2018"

[dependencies]
byteorder = "1.4"
candid = "0.7.10"
ciborium = { git = "https://github.com/enarx/ciborium", rev = "e719537c99b564c3674a56defe53713c702c6f46" }
comparable = { version = "0.5", features = ["derive"] }
crc32fast = "1.2.0"
dfn_candid = {path = "../../rust_canisters/dfn_candid"}
dfn_core = {path = "../../rust_canisters/dfn_core"}
dfn_http = {path = "../../rust_canisters/dfn_http"}
dfn_http_metrics = {path = "../../rust_canisters/dfn_http_metrics"}
dfn_protobuf = {path = "../../rust_canisters/dfn_protobuf"}
digest = "0.9.0"
hex = {version = "0.4.2", features = ["serde"] }
ic-base-types = { path="../../types/base_types" }
ic-constants = { path = "../../constants" }
ic-crypto-sha = {path = "../../crypto/sha/"}
ic-ic00-types = { path="../../types/ic00_types" }
ic-ledger-core = { path = "../ledger_core" }
ic-metrics-encoder = { path = "../../monitoring/metrics_encoder" }
ic-nns-constants = {path = "../../nns/constants" }
ic-utils = { path = "../../utils" }
intmap = { version = "0.8.0", features = ["serde"] }
lazy_static = "1.4.0"
on_wire = {path = "../../rust_canisters/on_wire"}
phantom_newtype = { path = "../../phantom_newtype" }
prost = "0.10.4"
prost-derive = "0.10"
serde = "1.0"
serde_bytes = "0.11"
serde_cbor = "0.11"

[[bin]]
name = "ledger-canister"
path = "src/main.rs"

[[bin]]
name = "ledger-archive-node-canister"
path = "src/archive_node.rs"

[dev-dependencies]
canister-test = {path = "../../rust_canisters/canister_test"}
ed25519-dalek = "1.0.1"
ic-canister-client = {path = "../../canister_client/"}
ic-test-utilities-compare-dirs = { path = "../../test_utilities/compare_dirs" }
ledger-canister-protobuf-generator = { path = "./protobuf_generator" }
rand_chacha = "0.2.2"
rand_core = "0.5.1"
tempfile = "3.1.0"

[[test]]
name = "test"
path = "test/test.rs"

[[test]]
name = "check_generated_files"
path = "test/check_generated_files.rs"

[[bin]]
name = "test-notified"
path = "test/notified.rs"

[features]
notify-method = []
test = ["ic-base-types/test"]
