[package]
name = "ic-nns-inspector"
version = "0.1.0"
edition = "2018"


[dependencies]
prost = "0.9.0"
structopt = "0.3.20"
hex = "0.4.3"
ic-nns-constants={path="../constants"}
stable_reader = {path="../../rust_canisters/stable_reader"}
ic-base-types={path="../../types/base_types"}
serde_cbor = "0.11.1"
csv = "1.1"
ic-nns-governance={path="../governance"}
serde = "1.0"
ledger-canister={path="../../rosetta-api/ledger_canister"}
ic-nns-gtc={path="../gtc"}
