[package]
name = "log_analyzer"
version = "0.8.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
regex = "1.3.9"

[dev-dependencies]
lazy_static = "1.4.0"
criterion = "0.3"
structopt = "0.3"

[[example]]
name = "logscan"
path = "examples/logscan.rs"

[[bench]]
name = "speed"
harness = false
