---

- set_fact: elasticsearch_hosts=elasticsearch.testnet.dfinity.systems:443
  when: elasticsearch_hosts is undefined

- name: import tasks assert
  import_tasks: "assert.yml"
  tags:
    - boundary_node_vm

- name: import tasks install
  import_tasks: "install.yml"
  tags:
    - boundary_node_vm


