[package]
name = "ic-registry-replicator"
version = "0.1.0"
edition = "2018"

[dependencies]
ic-config = { path = "../../config" }
ic-crypto-utils-threshold-sig = { path = "../../crypto/utils/threshold_sig" }
ic-interfaces = { path = "../../interfaces" }
ic-logger = { path = "../../monitoring/logger" }
ic-metrics = { path = "../../monitoring/metrics" }
ic-protobuf = { path = "../../protobuf" }
ic-registry-client = { path = "../../registry/client" }
ic-registry-client-helpers = { path = "../../registry/helpers" }
ic-registry-common = { path = "../../registry/common" }
ic-registry-keys = { path = "../../registry/keys" }
ic-registry-routing-table = { path = "../../registry/routing_table" }
ic-types = { path = "../../types/types" }
prost = "0.9.0"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
tokio = { version = "1.15.0", features = ["full"] }
url = "2.1.1"

[lib]
name = "ic_registry_replicator"
path = "src/registry_replicator.rs"

