[package]
name = "ic-ledger-core"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2018"

[dependencies]
candid = "0.7.10"
dfn_candid = { path = "../../rust_canisters/dfn_candid" }
dfn_core = { path = "../../rust_canisters/dfn_core" }
hex = "0.4.2"
ic-base-types = { path = "../../types/base_types" }
ic-crypto-sha = { path = "../../crypto/sha/" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-utils = { path = "../../utils" }
on_wire = { path = "../../rust_canisters/on_wire" }
serde = "1.0"
serde_bytes = "0.11"
