[package]
name = "ic-artifact-manager"
version = "0.8.0"
edition = "2018"

[dependencies]
bincode = "1.2.1"
ic-consensus-message = { path = "../consensus/message" }
ic-constants = { path = "../constants" }
ic-crypto-hash = { path = "../crypto/hash" }
ic-ecdsa-object = { path = "../consensus/ecdsa_object" }
ic-interfaces = { path = "../interfaces" }
ic-logger = { path = "../monitoring/logger" }
ic-metrics = { path = "../monitoring/metrics" }
ic-types = { path = "../types/types" }
crossbeam-channel = "0.5.0"
slog = { version = "2.5.2", features = ["nested-values", "max_level_trace", "release_max_level_debug"] }
prometheus = { version = "0.12.0", features = [ "process" ] }
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.54"

[dev-dependencies]
ic-config = { path = "../config" }
ic-artifact-pool = { path = "../artifact_pool" }
ic-test-utilities = { path = "../test_utilities" }
assert_matches = "1.3.0"

[features]
malicious_code = []
